-- FGF YouTube evidence ingestion schema.
-- Candidate claims remain separate from canonical claims.
create table if not exists public.video_database (
  id bigint generated by default as identity primary key,
  video_id text not null unique,
  playlist_id text,
  playlist_index integer,
  title text not null,
  video_url text not null,
  description text,
  published_at timestamptz,
  duration_seconds integer,
  channel_id text,
  channel_title text,
  processing_status text not null default 'indexed',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.video_claim_candidates (
  id bigint generated by default as identity primary key,
  video_database_id bigint references public.video_database(id) on delete cascade,
  video_id text not null,
  claim_text text not null,
  category text,
  claim_type text,
  evidence_tier integer not null default 3,
  confidence numeric(5,4),
  status text not null default 'candidate',
  source_url text,
  evidence_excerpt text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(video_id, claim_text)
);

create table if not exists public.video_processing_runs (
  id bigint generated by default as identity primary key,
  playlist_id text,
  video_id text,
  stage text not null,
  status text not null,
  details jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists idx_video_claim_candidates_status on public.video_claim_candidates(status);
create index if not exists idx_video_claim_candidates_video on public.video_claim_candidates(video_id);
create index if not exists idx_video_database_playlist on public.video_database(playlist_id, playlist_index);
